# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3c0f30aef7e9686c247abcbea6d145392ae68c4dc113d00626c7c283cb758411d03d074aaab1aed16252546a9b1326807e570c092ce952fe8c26e82905d3909

test:
  secret_key_base: b51e92f5bb0c1cf0023997aaccc76ac71c5420021dc42886c3273b22b58cb94655e9fba8f56fabf8758eda7fb5e6726133d08c48af7417c184aeaa1194f59b63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  rollbar_key_base: <%= ENV["ROLLBAR_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  rollbar_key_base: <%= ENV["ROLLBAR_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
