# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 100) do

  create_table "addresses", :force => true do |t|
    t.column "location_id",    :integer
    t.column "line1",          :string
    t.column "line2",          :string
    t.column "city",           :string,  :limit => 64
    t.column "state_abbrev",   :string
    t.column "zip",            :string
    t.column "address_type",   :string
    t.column "legacy_code",    :string,  :limit => 10
    t.column "legacy_subcode", :string,  :limit => 10
    t.column "fmp2_code",      :string,  :limit => 10
    t.column "latitude",       :decimal,               :precision => 9, :scale => 6
    t.column "longitude",      :decimal,               :precision => 9, :scale => 6
  end

  add_index "addresses", ["location_id"], :name => "location_id"

  create_table "agencies", :force => true do |t|
    t.column "agency_category_id", :integer
    t.column "result_type_id",     :integer
    t.column "name",               :string
    t.column "name2",              :string
    t.column "description",        :text
    t.column "data_source",        :string
    t.column "is_active",          :boolean
    t.column "url",                :string
    t.column "url_title",          :string
    t.column "url2",               :string
    t.column "url2_title",         :string
    t.column "comments",           :text
    t.column "services_provided",  :text
    t.column "use_for_counseling", :boolean
    t.column "created_at",         :datetime
    t.column "updated_at",         :datetime
    t.column "updated_by",         :string
    t.column "legacy_code",        :string,   :limit => 10
    t.column "legacy_status",      :string
    t.column "legacy_category1",   :string
    t.column "legacy_category2",   :string
    t.column "fmp2_code",          :string,   :limit => 10
    t.column "pha_contact_name",   :string
    t.column "pha_contact_title",  :string
    t.column "pha_contact_phone",  :string,   :limit => 20
    t.column "pha_contact_email",  :string
  end

  add_index "agencies", ["agency_category_id"], :name => "agency_category_id"
  add_index "agencies", ["result_type_id"], :name => "result_type_id"

  create_table "agency_categories", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "assistances", :force => true do |t|
    t.column "name", :string
  end

  create_table "assistances_partners", :id => false, :force => true do |t|
    t.column "partner_id",    :integer
    t.column "assistance_id", :integer
  end

  add_index "assistances_partners", ["partner_id"], :name => "partner_id"
  add_index "assistances_partners", ["assistance_id"], :name => "assistance_id"

  create_table "cities", :force => true do |t|
    t.column "name",         :string
    t.column "county_id",    :integer
    t.column "state_abbrev", :string
  end

  add_index "cities", ["name", "county_id"], :name => "index_cities_on_name_and_county_id", :unique => true
  add_index "cities", ["county_id"], :name => "county_id"

  create_table "cities_zips", :id => false, :force => true do |t|
    t.column "city_id",   :integer,              :null => false
    t.column "zipcode",   :string,  :limit => 5, :null => false
    t.column "city_type", :string,  :limit => 1
  end

  add_index "cities_zips", ["zipcode", "city_id"], :name => "idx_cities_zips_on_zip_and_city"

  create_table "claim_types", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "comments", :force => true do |t|
    t.column "title",            :string,   :limit => 50, :default => ""
    t.column "comment",          :text
    t.column "created_at",       :datetime,                               :null => false
    t.column "commentable_id",   :integer,                :default => 0,  :null => false
    t.column "commentable_type", :string,   :limit => 15,                 :null => false
    t.column "user_id",          :integer,                :default => 0,  :null => false
  end

  add_index "comments", ["user_id"], :name => "user_id"

  create_table "contents", :force => true do |t|
    t.column "url",        :string
    t.column "title",      :string
    t.column "content",    :text
    t.column "created_at", :string
    t.column "updated_at", :datetime
    t.column "updated_by", :string
    t.column "parent_id",  :integer
    t.column "lft",        :integer
    t.column "rgt",        :integer
    t.column "is_active",  :boolean
  end

  add_index "contents", ["parent_id"], :name => "parent_id"

  create_table "counselings", :force => true do |t|
    t.column "zipcode",                 :string
    t.column "employment_start",        :date
    t.column "employment_end",          :date
    t.column "is_divorce_related",      :boolean
    t.column "is_survivorship_related", :boolean
    t.column "work_state_abbrev",       :string
    t.column "hq_state_abbrev",         :string
    t.column "pension_state_abbrev",    :string
    t.column "is_over_60",              :boolean
    t.column "monthly_income",          :decimal,  :precision => 10, :scale => 2
    t.column "number_in_household",     :integer
    t.column "employer_type_id",        :integer
    t.column "federal_plan_id",         :integer
    t.column "military_service_id",     :integer
    t.column "military_branch_id",      :integer
    t.column "military_employer_id",    :integer
    t.column "pension_earner_id",       :integer
    t.column "state_abbrev",            :string
    t.column "county_id",               :integer
    t.column "city_id",                 :integer
    t.column "created_at",              :datetime
    t.column "is_afscme_member",        :boolean
    t.column "selected_plan_id",        :integer
    t.column "currently_employed",      :boolean
    t.column "plan_name",               :string
    t.column "agency_name",             :string
    t.column "job_function",            :string
    t.column "feedback_email",          :string
    t.column "lost_plan",               :boolean
    t.column "behalf",                  :string
    t.column "behalf_other",            :string
    t.column "gender",                  :string
    t.column "marital_status",          :string
    t.column "age",                     :integer
    t.column "enthinicty",              :string
  end

  add_index "counselings", ["employer_type_id"], :name => "employer_type_id"
  add_index "counselings", ["federal_plan_id"], :name => "federal_plan_id"
  add_index "counselings", ["military_service_id"], :name => "military_service_id"
  add_index "counselings", ["military_branch_id"], :name => "military_branch_id"
  add_index "counselings", ["military_employer_id"], :name => "military_employer_id"
  add_index "counselings", ["pension_earner_id"], :name => "pension_earner_id"
  add_index "counselings", ["county_id"], :name => "county_id"
  add_index "counselings", ["city_id"], :name => "city_id"
  add_index "counselings", ["selected_plan_id"], :name => "selected_plan_id"

  create_table "counties", :force => true do |t|
    t.column "name",         :string
    t.column "fips_code",    :string
    t.column "state_abbrev", :string
  end

  add_index "counties", ["fips_code", "state_abbrev"], :name => "index_counties_on_fips_code_and_state_abbrev", :unique => true

  create_table "dup_temp", :id => false, :force => true do |t|
    t.column "AgencyID",        :integer, :default => 0, :null => false
    t.column "Agency Name",     :string
    t.column "Agency Name 2",   :string
    t.column "LocationID",      :integer, :default => 0, :null => false
    t.column "Location Name",   :string
    t.column "Location Name 2", :string
  end

  create_table "employee_types", :force => true do |t|
    t.column "name", :string
  end

  create_table "employer_types", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "expertises", :force => true do |t|
    t.column "name", :string
    t.column "form", :string
  end

  create_table "expertises_partners", :id => false, :force => true do |t|
    t.column "expertise_id", :integer
    t.column "partner_id",   :integer
  end

  add_index "expertises_partners", ["expertise_id"], :name => "expertise_id"
  add_index "expertises_partners", ["partner_id"], :name => "partner_id"

  create_table "federal_plans", :force => true do |t|
    t.column "name",               :string
    t.column "position",           :integer
    t.column "parent_id",          :integer
    t.column "associated_plan_id", :integer
  end

  add_index "federal_plans", ["parent_id"], :name => "parent_id"
  add_index "federal_plans", ["associated_plan_id"], :name => "associated_plan_id"

  create_table "fee_arrangements", :force => true do |t|
    t.column "name", :string
  end

  create_table "fee_arrangements_partners", :id => false, :force => true do |t|
    t.column "partner_id",         :integer
    t.column "fee_arrangement_id", :integer
  end

  add_index "fee_arrangements_partners", ["partner_id"], :name => "partner_id"
  add_index "fee_arrangements_partners", ["fee_arrangement_id"], :name => "fee_arrangement_id"

  create_table "feedbacks", :force => true do |t|
    t.column "name",         :string
    t.column "email",        :string
    t.column "phone",        :string
    t.column "availability", :string
    t.column "category",     :string
    t.column "feedback",     :text
    t.column "is_resolved",  :boolean,  :default => false
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "fmp1_agencies", :id => false, :force => true do |t|
    t.column "agency_name_1",              :string
    t.column "agency_name_2",              :string
    t.column "comments",                   :text
    t.column "con_ad_drop_city",           :string
    t.column "con_ad_drop_state",          :string
    t.column "con_ad_drop_street_1",       :string
    t.column "con_ad_drop_street_2",       :string
    t.column "con_ad_drop_zip",            :string
    t.column "con_ad_mail_city",           :string
    t.column "con_ad_mail_state",          :string
    t.column "con_ad_mail_street_1",       :string
    t.column "con_ad_mail_street_2",       :string
    t.column "con_ad_mail_zip",            :string
    t.column "con_email",                  :string
    t.column "con_ext_local",              :string
    t.column "con_ext_toll_free",          :string
    t.column "con_ext_tty",                :string
    t.column "con_phone_fax",              :string
    t.column "con_phone_local",            :string
    t.column "con_phone_toll_free",        :string
    t.column "con_phone_tty",              :string
    t.column "con_pubs_email",             :string
    t.column "con_pubs_ext_local",         :string
    t.column "con_pubs_ext_toll_free",     :string
    t.column "con_pubs_ext_tty",           :string
    t.column "con_pubs_fax",               :string
    t.column "con_pubs_local",             :string
    t.column "con_pubs_toll_free",         :string
    t.column "con_pubs_tty",               :string
    t.column "con_pubs_url",               :string
    t.column "con_url_1",                  :string
    t.column "con_url_2",                  :string
    t.column "con_url_title_1",            :string
    t.column "con_url_title_2",            :string
    t.column "descriptive_summary",        :text
    t.column "hours_o_operation",          :string
    t.column "logisitics",                 :text
    t.column "pension_system",             :string
    t.column "res_max_poverty_percent",    :decimal,  :precision => 9, :scale => 2
    t.column "res_min_age",                :decimal,  :precision => 5, :scale => 2
    t.column "Serial",                     :integer,                                :default => 0,    :null => false
    t.column "services_provided",          :text
    t.column "source_o_data",              :string
    t.column "stamp_creation",             :datetime
    t.column "stamp_modification",         :datetime
    t.column "sts_status_flag",            :string
    t.column "user_modification",          :string
    t.column "help_book_macro",            :string
    t.column "help_book_micro",            :string
    t.column "service_provider",           :string
    t.column "other_services_provided",    :string
    t.column "sts_status",                 :string
    t.column "non_pension_resource_types", :string
    t.column "military_branches",          :string
    t.column "public_plan_type",           :string
    t.column "import_to_pha",              :boolean,                                :default => true, :null => false
  end

  create_table "fmp1_subagencies", :id => false, :force => true do |t|
    t.column "AgencyId",                   :integer
    t.column "agency_name_1",              :string
    t.column "agency_name_2",              :string
    t.column "comments",                   :text
    t.column "con_ad_drop_city",           :string
    t.column "con_ad_drop_state",          :string
    t.column "con_ad_drop_street_1",       :string
    t.column "con_ad_drop_street_2",       :string
    t.column "con_ad_drop_zip",            :string
    t.column "con_ad_mail_city",           :string
    t.column "con_ad_mail_state",          :string
    t.column "con_ad_mail_street_1",       :string
    t.column "con_ad_mail_street_2",       :string
    t.column "con_ad_mail_zip",            :string
    t.column "con_email",                  :string
    t.column "con_ext_local",              :string
    t.column "con_ext_toll_free",          :string
    t.column "con_ext_tty",                :string
    t.column "con_phone_fax",              :string
    t.column "con_phone_local",            :string
    t.column "con_phone_toll_free",        :string
    t.column "con_phone_tty",              :string
    t.column "con_pubs_email",             :string
    t.column "con_pubs_ext_local",         :string
    t.column "con_pubs_ext_toll_free",     :string
    t.column "con_pubs_ext_tty",           :string
    t.column "con_pubs_fax",               :string
    t.column "con_pubs_local",             :string
    t.column "con_pubs_toll_free",         :string
    t.column "con_pubs_tty",               :string
    t.column "con_pubs_url",               :string
    t.column "con_url_1",                  :string
    t.column "con_url_2",                  :string
    t.column "con_url_title_1",            :string
    t.column "con_url_title_2",            :string
    t.column "descriptive_summary",        :text
    t.column "hours_o_operation",          :string
    t.column "logisitics",                 :text
    t.column "Serial",                     :integer,  :default => 0, :null => false
    t.column "services_provided",          :text
    t.column "source_o_data",              :string
    t.column "stamp_creation",             :datetime
    t.column "stamp_modification",         :datetime
    t.column "sts_status_flag",            :string
    t.column "user_modification",          :string
    t.column "other_services_provided",    :string
    t.column "sts_status",                 :string
    t.column "non_pension_resource_types", :string
  end

  create_table "fmp2", :id => false, :force => true do |t|
    t.column "newDbSerial",                  :integer, :default => 0, :null => false
    t.column "ResultType",                   :string
    t.column "OldPHA_AgencySerialNumber",    :integer
    t.column "OldPHA_BabiesSerialNumber",    :integer
    t.column "AgencyName1",                  :string
    t.column "AgencyName2",                  :string
    t.column "PlanDescription",              :text
    t.column "Comments",                     :text
    t.column "AgencyMailStreet1",            :string
    t.column "AgencyMailStreet2",            :string
    t.column "AgencyMailCity",               :string
    t.column "AgencyMailState",              :string
    t.column "AgencyMailZip",                :string
    t.column "AgencyDropInStreet1",          :string
    t.column "AgencyDropInStreet2",          :string
    t.column "AgencyDropInCity",             :string
    t.column "AgencyDropInState",            :string
    t.column "AgencyDropInZip",              :string
    t.column "AgencyTollFreePhone",          :string
    t.column "AgencyLocalPhone",             :string
    t.column "AgencyFax",                    :string
    t.column "AgencyTTYPhone",               :string
    t.column "AgencyTollFreePhoneExt",       :string
    t.column "AgencyLocalPhoneExt",          :string
    t.column "AgencyTTYPhoneExt",            :string
    t.column "AgencyEmail",                  :string
    t.column "AgencyURL",                    :string
    t.column "PlanURL",                      :string
    t.column "AgencyURLTitle",               :string
    t.column "PlanURLTitle",                 :string
    t.column "AgencyPubsTollFreePhone",      :string
    t.column "AgencyPubsLocalPhone",         :string
    t.column "AgencyPubsTTYPhone",           :string
    t.column "AgencyPubsTollFreePhoneExt",   :string
    t.column "AgencyPubsLocalPhoneExt",      :string
    t.column "AgencyPubsTTYPhoneExt",        :string
    t.column "AgencyPubsURL",                :string
    t.column "RecordStatus",                 :string
    t.column "AgencyPubsURLTitle",           :string
    t.column "SPDURL",                       :string
    t.column "SPDURLTitle",                  :string
    t.column "PlanStartDate",                :date
    t.column "PlanEndDate",                  :date
    t.column "CoveredEmployee",              :text
    t.column "PlanType1",                    :string
    t.column "PlanType2",                    :string
    t.column "PlanType3",                    :string
    t.column "PlanName1",                    :string
    t.column "PlanName2",                    :string
    t.column "TPAURL",                       :string
    t.column "TPAURL_Title",                 :string
    t.column "CatchallEmployees",            :text
    t.column "ServiceGeographyType",         :string
    t.column "GeographicServiceInformation", :string
    t.column "GovtCounty",                   :string
    t.column "GovtSpDist",                   :string
    t.column "GovtState",                    :string
    t.column "GovtEmployerType",             :string
    t.column "MultipleOffices",              :string
    t.column "primary_serial",               :integer
    t.column "loc_serial",                   :integer
    t.column "plan_serial",                  :integer
  end

  create_table "geo_areas", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "help_additional_areas", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "images", :force => true do |t|
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "filename",     :string
    t.column "content_type", :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "aspect_ratio", :float
  end

  add_index "images", ["parent_id"], :name => "parent_id"

  create_table "jurisdictions", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "location_plan_relationships", :force => true do |t|
    t.column "location_id", :integer
    t.column "plan_id",     :integer
    t.column "is_hq",       :boolean
  end

  add_index "location_plan_relationships", ["location_id"], :name => "location_id"
  add_index "location_plan_relationships", ["plan_id"], :name => "plan_id"

  create_table "locations", :force => true do |t|
    t.column "agency_id",          :integer
    t.column "name",               :string
    t.column "name2",              :string
    t.column "is_hq",              :boolean
    t.column "is_provider",        :boolean
    t.column "tollfree",           :string,   :limit => 20
    t.column "tollfree_ext",       :string,   :limit => 10
    t.column "phone",              :string,   :limit => 20
    t.column "phone_ext",          :string,   :limit => 10
    t.column "tty",                :string,   :limit => 20
    t.column "tty_ext",            :string,   :limit => 10
    t.column "fax",                :string,   :limit => 20
    t.column "email",              :string
    t.column "hours_of_operation", :string
    t.column "logistics",          :string
    t.column "updated_at",         :datetime
    t.column "legacy_code",        :string,   :limit => 10
    t.column "legacy_subcode",     :string,   :limit => 10
    t.column "fmp2_code",          :string,   :limit => 10
    t.column "updated_by",         :string
    t.column "url",                :string
    t.column "url_title",          :string
    t.column "url2",               :string
    t.column "url2_title",         :string
    t.column "position",           :integer
    t.column "pha_contact_name",   :string
    t.column "pha_contact_title",  :string
    t.column "pha_contact_phone",  :string,   :limit => 20
    t.column "pha_contact_email",  :string
    t.column "comment",            :text
    t.column "is_active",          :boolean,                :default => true
  end

  add_index "locations", ["agency_id"], :name => "agency_id"

  create_table "military_branches", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "military_employers", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "military_services", :force => true do |t|
    t.column "name",      :string
    t.column "position",  :integer
    t.column "is_active", :boolean, :default => true
  end

  create_table "news", :force => true do |t|
    t.column "title",        :string
    t.column "intro",        :text
    t.column "article_url",  :string
    t.column "source_url",   :string
    t.column "is_internal",  :boolean
    t.column "body",         :text
    t.column "publish_date", :date
    t.column "archive_date", :date
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "updated_by",   :string
    t.column "position",     :integer
  end

  create_table "npln_additional_areas", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "npln_participation_levels", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "page_emails", :force => true do |t|
    t.column "page_title",      :string
    t.column "link",            :string
    t.column "name",            :string
    t.column "email",           :string
    t.column "recipient_name",  :string
    t.column "recipient_email", :string
    t.column "message",         :text
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "pal_additional_areas", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "pal_participation_levels", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "participations", :force => true do |t|
    t.column "name", :string
  end

  create_table "participations_partners", :id => false, :force => true do |t|
    t.column "partner_id",       :integer
    t.column "participation_id", :integer
  end

  add_index "participations_partners", ["partner_id"], :name => "partner_id"
  add_index "participations_partners", ["participation_id"], :name => "participation_id"

  create_table "partners", :force => true do |t|
    t.column "first_name",                                   :string,  :limit => 80
    t.column "last_name",                                    :string,  :limit => 80
    t.column "company",                                      :string
    t.column "line_1",                                       :string
    t.column "line_2",                                       :string
    t.column "city",                                         :string,  :limit => 50
    t.column "state_abbrev",                                 :string,  :limit => 2
    t.column "zip_code",                                     :string,  :limit => 10
    t.column "phone",                                        :string,  :limit => 20
    t.column "fax",                                          :string,  :limit => 20
    t.column "email",                                        :string
    t.column "url",                                          :string
    t.column "other_info",                                   :text
    t.column "wants_npln",                                   :boolean,               :default => false
    t.column "wants_pal",                                    :boolean,               :default => false, :null => false
    t.column "preferred_method_of_contact",                  :integer
    t.column "fee_for_initial_consultation",                 :string
    t.column "hourly_continuous_fee",                        :string
    t.column "professional_certifications_and_affiliations", :string
    t.column "has_other_areas_of_expertise",                 :boolean
    t.column "other_areas_of_expertise",                     :string
    t.column "dr_lawyer",                                    :boolean,               :default => false
    t.column "has_other_level_of_participation",             :boolean,               :default => false
    t.column "other_level_of_participation",                 :string
    t.column "law_practice_states",                          :string
    t.column "law_practice_circuits",                        :string
    t.column "us_supreme_court",                             :boolean,               :default => false
    t.column "malpractice_insurance",                        :boolean,               :default => false
  end

  create_table "partners_claim_types", :id => false, :force => true do |t|
    t.column "partner_id",    :integer, :null => false
    t.column "claim_type_id", :integer, :null => false
  end

  add_index "partners_claim_types", ["claim_type_id", "partner_id"], :name => "index_partners_claim_types_on_claim_type_id_and_partner_id"

  create_table "partners_geo_areas", :force => true do |t|
    t.column "partner_id",  :integer
    t.column "geo_area_id", :integer
  end

  add_index "partners_geo_areas", ["partner_id"], :name => "partner_id"
  add_index "partners_geo_areas", ["geo_area_id"], :name => "geo_area_id"

  create_table "partners_help_additional_areas", :id => false, :force => true do |t|
    t.column "partner_id",              :integer, :null => false
    t.column "help_additional_area_id", :integer, :null => false
  end

  add_index "partners_help_additional_areas", ["help_additional_area_id", "partner_id"], :name => "partners_help_areas"

  create_table "partners_jurisdictions", :force => true do |t|
    t.column "partner_id",      :integer
    t.column "jurisdiction_id", :integer
  end

  add_index "partners_jurisdictions", ["partner_id"], :name => "partner_id"
  add_index "partners_jurisdictions", ["jurisdiction_id"], :name => "jurisdiction_id"

  create_table "partners_npln_additional_areas", :id => false, :force => true do |t|
    t.column "partner_id",              :integer, :null => false
    t.column "npln_additional_area_id", :integer, :null => false
  end

  add_index "partners_npln_additional_areas", ["npln_additional_area_id", "partner_id"], :name => "partners_npln_areas"

  create_table "partners_npln_participation_levels", :id => false, :force => true do |t|
    t.column "partner_id",                  :integer, :null => false
    t.column "npln_participation_level_id", :integer, :null => false
  end

  add_index "partners_npln_participation_levels", ["npln_participation_level_id", "partner_id"], :name => "partners_npln_participations"

  create_table "partners_pal_additional_areas", :id => false, :force => true do |t|
    t.column "partner_id",             :integer, :null => false
    t.column "pal_additional_area_id", :integer, :null => false
  end

  add_index "partners_pal_additional_areas", ["pal_additional_area_id", "partner_id"], :name => "partners_pal_areas"

  create_table "partners_pal_participation_levels", :id => false, :force => true do |t|
    t.column "partner_id",                 :integer, :null => false
    t.column "pal_participation_level_id", :integer, :null => false
  end

  add_index "partners_pal_participation_levels", ["pal_participation_level_id", "partner_id"], :name => "partners_pal_participations"

  create_table "partners_plan_types", :id => false, :force => true do |t|
    t.column "partner_id",   :integer, :null => false
    t.column "plan_type_id", :integer, :null => false
  end

  add_index "partners_plan_types", ["plan_type_id", "partner_id"], :name => "index_partners_plan_types_on_plan_type_id_and_partner_id"

  create_table "partners_practices", :id => false, :force => true do |t|
    t.column "partner_id",  :integer
    t.column "practice_id", :integer
  end

  add_index "partners_practices", ["partner_id"], :name => "partner_id"
  add_index "partners_practices", ["practice_id"], :name => "practice_id"

  create_table "partners_professions", :id => false, :force => true do |t|
    t.column "partner_id",    :integer, :null => false
    t.column "profession_id", :integer, :null => false
  end

  add_index "partners_professions", ["profession_id", "partner_id"], :name => "index_partners_professions_on_profession_id_and_partner_id"

  create_table "partners_referral_fees", :id => false, :force => true do |t|
    t.column "partner_id",      :integer, :null => false
    t.column "referral_fee_id", :integer, :null => false
  end

  add_index "partners_referral_fees", ["referral_fee_id", "partner_id"], :name => "index_partners_referral_fees_on_referral_fee_id_and_partner_id"

  create_table "partners_search_plan_types", :id => false, :force => true do |t|
    t.column "partner_id",          :integer, :null => false
    t.column "search_plan_type_id", :integer, :null => false
  end

  add_index "partners_search_plan_types", ["search_plan_type_id", "partner_id"], :name => "partners_search_plans"

  create_table "partners_sponsor_types", :id => false, :force => true do |t|
    t.column "partner_id",      :integer, :null => false
    t.column "sponsor_type_id", :integer, :null => false
  end

  add_index "partners_sponsor_types", ["sponsor_type_id", "partner_id"], :name => "index_partners_sponsor_types_on_sponsor_type_id_and_partner_id"

  create_table "pension_earners", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "plan_catch_all_employees", :force => true do |t|
    t.column "plan_id",          :integer
    t.column "employee_type_id", :integer
    t.column "position",         :integer
  end

  add_index "plan_catch_all_employees", ["plan_id"], :name => "plan_id"
  add_index "plan_catch_all_employees", ["employee_type_id"], :name => "employee_type_id"

  create_table "plan_categories", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "plan_types", :force => true do |t|
    t.column "name",        :string
    t.column "position",    :integer
    t.column "use_for_pal", :boolean
  end

  create_table "plans", :force => true do |t|
    t.column "agency_id",             :integer
    t.column "name",                  :string
    t.column "name2",                 :string
    t.column "description",           :text
    t.column "comments",              :text
    t.column "start_date",            :date
    t.column "end_date",              :date
    t.column "covered_employees",     :text
    t.column "plan_type1",            :string
    t.column "plan_type2",            :string
    t.column "plan_type3",            :string
    t.column "url",                   :string
    t.column "url_title",             :string
    t.column "admin_url",             :string
    t.column "admin_url_title",       :string
    t.column "tpa_url",               :string
    t.column "tpa_url_title",         :string
    t.column "spd_url",               :string
    t.column "spd_url_title",         :string
    t.column "govt_employee_type",    :string
    t.column "fmp2_code",             :string
    t.column "legacy_category",       :string
    t.column "legacy_status",         :string
    t.column "updated_at",            :datetime
    t.column "updated_by",            :string
    t.column "email",                 :string
    t.column "position",              :integer
    t.column "pha_contact_name",      :string
    t.column "pha_contact_title",     :string
    t.column "pha_contact_phone",     :string,   :limit => 20
    t.column "pha_contact_email",     :string
    t.column "is_active",             :boolean,                :default => true
    t.column "previous_gov_employee", :string
    t.column "plan_category_id",      :integer
  end

  add_index "plans", ["agency_id"], :name => "agency_id"
  add_index "plans", ["plan_category_id"], :name => "plan_category_id"

  create_table "poverty_levels", :force => true do |t|
    t.column "year",                :integer
    t.column "number_in_household", :integer
    t.column "geographic",          :string
    t.column "fpl",                 :decimal, :precision => 8, :scale => 2
  end

  create_table "practices", :force => true do |t|
    t.column "name", :string
  end

  create_table "professions", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "publications", :force => true do |t|
    t.column "agency_id",    :integer
    t.column "tollfree",     :string,  :limit => 20
    t.column "tollfree_ext", :string,  :limit => 10
    t.column "phone",        :string,  :limit => 20
    t.column "phone_ext",    :string,  :limit => 10
    t.column "tty",          :string,  :limit => 20
    t.column "tty_ext",      :string,  :limit => 10
    t.column "fax",          :string,  :limit => 20
    t.column "email",        :string
    t.column "url",          :string
    t.column "url_title",    :string
    t.column "legacy_code",  :string,  :limit => 10
    t.column "fmp2_code",    :string,  :limit => 10
  end

  add_index "publications", ["agency_id"], :name => "agency_id"

  create_table "referral_fees", :force => true do |t|
    t.column "name",        :string
    t.column "position",    :integer
    t.column "use_for_pal", :boolean, :default => true
  end

  create_table "restrictions", :force => true do |t|
    t.column "agency_id",            :integer
    t.column "location_id",          :integer
    t.column "plan_id",              :integer
    t.column "minimum_age",          :integer
    t.column "max_poverty",          :integer
    t.column "special_district",     :string
    t.column "other_restrictions",   :text
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
    t.column "legacy_geo_states",    :string
    t.column "legacy_code",          :string,   :limit => 10
    t.column "legacy_subcode",       :string,   :limit => 10
    t.column "fmp2_code",            :string,   :limit => 10
    t.column "legacy_geo_counties",  :text
    t.column "legacy_geo_cities",    :text
    t.column "age_and_income",       :boolean
    t.column "age_restricted_phone", :string,   :limit => 20
  end

  add_index "restrictions", ["agency_id"], :name => "agency_id"
  add_index "restrictions", ["location_id"], :name => "location_id"
  add_index "restrictions", ["plan_id"], :name => "plan_id"

  create_table "restrictions_cities", :id => false, :force => true do |t|
    t.column "restriction_id", :integer, :null => false
    t.column "city_id",        :integer, :null => false
  end

  add_index "restrictions_cities", ["city_id", "restriction_id"], :name => "index_restrictions_cities_on_city_id_and_restriction_id"

  create_table "restrictions_counties", :id => false, :force => true do |t|
    t.column "restriction_id", :integer, :null => false
    t.column "county_id",      :integer, :null => false
  end

  add_index "restrictions_counties", ["county_id", "restriction_id"], :name => "index_restrictions_counties_on_county_id_and_restriction_id"

  create_table "restrictions_reload", :id => false, :force => true do |t|
    t.column "discriminatory_count",            :integer
    t.column "sp_display_babies_states",        :text
    t.column "sp_display_babies_counties",      :text
    t.column "sp_display_babies_cities",        :text
    t.column "sp_display_counseling_states",    :text
    t.column "sp_display_counseling_counties",  :text
    t.column "sp_display_counseling_cities",    :text
    t.column "res_geographic",                  :string
    t.column "res_geographic_meaning",          :string
    t.column "res_languages",                   :string
    t.column "res_max_age",                     :integer
    t.column "res_max_poverty_percent",         :decimal,  :precision => 8, :scale => 2
    t.column "res_military",                    :string
    t.column "res_min_age",                     :integer
    t.column "res_pop_number_o_family_members", :integer
    t.column "res_pov_guide_year",              :integer
    t.column "res_pov_threshold_household",     :integer
    t.column "res_pov_threshold_type",          :string
    t.column "res_residency",                   :string
    t.column "res_resident",                    :string
    t.column "res_restriction_categories",      :string
    t.column "sn",                              :integer,                                :default => 0, :null => false
    t.column "sn_o_baby",                       :integer
    t.column "sn_o_counseling",                 :integer
    t.column "stamp_creation",                  :datetime
    t.column "stamp_modification",              :datetime
    t.column "user_creation",                   :string
    t.column "user_modification",               :string
  end

  create_table "restrictions_states", :id => false, :force => true do |t|
    t.column "restriction_id", :integer,              :null => false
    t.column "state_abbrev",   :string,  :limit => 2, :null => false
  end

  add_index "restrictions_states", ["state_abbrev", "restriction_id"], :name => "index_restrictions_states_on_state_abbrev_and_restriction_id"

  create_table "restrictions_zips", :id => false, :force => true do |t|
    t.column "restriction_id", :integer,              :null => false
    t.column "zipcode",        :string,  :limit => 5, :null => false
  end

  add_index "restrictions_zips", ["zipcode", "restriction_id"], :name => "index_restrictions_zips_on_zipcode_and_restriction_id"

  create_table "result_types", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "roles", :force => true do |t|
    t.column "role_name",   :string
    t.column "description", :string
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "user_id", :integer
    t.column "role_id", :integer
  end

  add_index "roles_users", ["user_id"], :name => "user_id"
  add_index "roles_users", ["role_id"], :name => "role_id"

  create_table "search_plan_types", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "sponsor_types", :force => true do |t|
    t.column "name",           :string
    t.column "position",       :integer
    t.column "use_for_pal",    :boolean, :default => true
    t.column "use_for_search", :boolean, :default => false
    t.column "use_for_npln",   :boolean, :default => true
    t.column "use_for_help",   :boolean, :default => true
  end

  create_table "states", :id => false, :force => true do |t|
    t.column "abbrev", :string, :limit => 2,  :null => false
    t.column "name",   :string, :limit => 50
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "is_random_pass",            :boolean
  end

  create_table "zip_import", :id => false, :force => true do |t|
    t.column "zipcode",      :string,  :limit => 5,                                :null => false
    t.column "city",         :string,  :limit => 64
    t.column "county",       :string,  :limit => 64
    t.column "state_abbrev", :string,  :limit => 2
    t.column "zip_type",     :string,  :limit => 1
    t.column "city_type",    :string,  :limit => 1
    t.column "county_fips",  :string,  :limit => 5
    t.column "state_name",   :string,  :limit => 64
    t.column "state_fips",   :string,  :limit => 2
    t.column "msa_code",     :string,  :limit => 4
    t.column "area_code",    :string,  :limit => 16
    t.column "time_zone",    :string,  :limit => 16
    t.column "utc",          :decimal,               :precision => 3, :scale => 1
    t.column "dst",          :string,  :limit => 1
    t.column "latitude",     :decimal,               :precision => 9, :scale => 6
    t.column "longitude",    :decimal,               :precision => 9, :scale => 6
  end

  add_index "zip_import", ["zipcode"], :name => "index_zip_import_on_zipcode"
  add_index "zip_import", ["city"], :name => "index_zip_import_on_city"
  add_index "zip_import", ["county"], :name => "index_zip_import_on_county"
  add_index "zip_import", ["state_abbrev"], :name => "index_zip_import_on_state_abbrev"

  create_table "zips", :id => false, :force => true do |t|
    t.column "zipcode",      :string,  :null => false
    t.column "state_abbrev", :string
    t.column "county_id",    :integer
  end

  add_index "zips", ["county_id"], :name => "county_id"

  add_foreign_key "addresses", ["location_id"], "locations", ["id"], :name => "addresses_ibfk_1"

  add_foreign_key "agencies", ["agency_category_id"], "agency_categories", ["id"], :name => "agencies_ibfk_1"
  add_foreign_key "agencies", ["result_type_id"], "result_types", ["id"], :name => "agencies_ibfk_2"

  add_foreign_key "assistances_partners", ["partner_id"], "partners", ["id"], :name => "assistances_partners_ibfk_1"
  add_foreign_key "assistances_partners", ["assistance_id"], "assistances", ["id"], :name => "assistances_partners_ibfk_2"

  add_foreign_key "cities", ["county_id"], "counties", ["id"], :name => "cities_ibfk_1"

  add_foreign_key "cities_zips", ["city_id"], "cities", ["id"], :name => "cities_zips_ibfk_1"

  add_foreign_key "comments", ["user_id"], "users", ["id"], :name => "comments_ibfk_1"

  add_foreign_key "contents", ["parent_id"], "contents", ["id"], :name => "contents_ibfk_1"

  add_foreign_key "counselings", ["employer_type_id"], "employer_types", ["id"], :name => "counselings_ibfk_1"
  add_foreign_key "counselings", ["federal_plan_id"], "federal_plans", ["id"], :name => "counselings_ibfk_2"
  add_foreign_key "counselings", ["military_service_id"], "military_services", ["id"], :name => "counselings_ibfk_3"
  add_foreign_key "counselings", ["military_branch_id"], "military_branches", ["id"], :name => "counselings_ibfk_4"
  add_foreign_key "counselings", ["military_employer_id"], "military_employers", ["id"], :name => "counselings_ibfk_5"
  add_foreign_key "counselings", ["pension_earner_id"], "pension_earners", ["id"], :name => "counselings_ibfk_6"
  add_foreign_key "counselings", ["county_id"], "counties", ["id"], :name => "counselings_ibfk_7"
  add_foreign_key "counselings", ["city_id"], "cities", ["id"], :name => "counselings_ibfk_8"
  add_foreign_key "counselings", ["selected_plan_id"], "plans", ["id"], :name => "counselings_ibfk_9"

  add_foreign_key "expertises_partners", ["expertise_id"], "expertises", ["id"], :name => "expertises_partners_ibfk_1"
  add_foreign_key "expertises_partners", ["partner_id"], "partners", ["id"], :name => "expertises_partners_ibfk_2"

  add_foreign_key "federal_plans", ["parent_id"], "federal_plans", ["id"], :name => "federal_plans_ibfk_1"
  add_foreign_key "federal_plans", ["associated_plan_id"], "plans", ["id"], :name => "federal_plans_ibfk_2"

  add_foreign_key "fee_arrangements_partners", ["partner_id"], "partners", ["id"], :name => "fee_arrangements_partners_ibfk_1"
  add_foreign_key "fee_arrangements_partners", ["fee_arrangement_id"], "fee_arrangements", ["id"], :name => "fee_arrangements_partners_ibfk_2"

  add_foreign_key "images", ["parent_id"], "images", ["id"], :name => "images_ibfk_1"

  add_foreign_key "location_plan_relationships", ["location_id"], "locations", ["id"], :name => "location_plan_relationships_ibfk_1"
  add_foreign_key "location_plan_relationships", ["plan_id"], "plans", ["id"], :name => "location_plan_relationships_ibfk_2"

  add_foreign_key "locations", ["agency_id"], "agencies", ["id"], :name => "locations_ibfk_1"

  add_foreign_key "participations_partners", ["partner_id"], "partners", ["id"], :name => "participations_partners_ibfk_1"
  add_foreign_key "participations_partners", ["participation_id"], "participations", ["id"], :name => "participations_partners_ibfk_2"

  add_foreign_key "partners_claim_types", ["partner_id"], "partners", ["id"], :name => "partners_claim_types_ibfk_1"
  add_foreign_key "partners_claim_types", ["claim_type_id"], "claim_types", ["id"], :name => "partners_claim_types_ibfk_2"

  add_foreign_key "partners_geo_areas", ["partner_id"], "partners", ["id"], :name => "partners_geo_areas_ibfk_1"
  add_foreign_key "partners_geo_areas", ["geo_area_id"], "geo_areas", ["id"], :name => "partners_geo_areas_ibfk_2"

  add_foreign_key "partners_help_additional_areas", ["partner_id"], "partners", ["id"], :name => "partners_help_additional_areas_ibfk_1"
  add_foreign_key "partners_help_additional_areas", ["help_additional_area_id"], "help_additional_areas", ["id"], :name => "partners_help_additional_areas_ibfk_2"

  add_foreign_key "partners_jurisdictions", ["partner_id"], "partners", ["id"], :name => "partners_jurisdictions_ibfk_1"
  add_foreign_key "partners_jurisdictions", ["jurisdiction_id"], "jurisdictions", ["id"], :name => "partners_jurisdictions_ibfk_2"

  add_foreign_key "partners_npln_additional_areas", ["partner_id"], "partners", ["id"], :name => "partners_npln_additional_areas_ibfk_1"
  add_foreign_key "partners_npln_additional_areas", ["npln_additional_area_id"], "npln_additional_areas", ["id"], :name => "partners_npln_additional_areas_ibfk_2"

  add_foreign_key "partners_npln_participation_levels", ["partner_id"], "partners", ["id"], :name => "partners_npln_participation_levels_ibfk_1"
  add_foreign_key "partners_npln_participation_levels", ["npln_participation_level_id"], "npln_participation_levels", ["id"], :name => "partners_npln_participation_levels_ibfk_2"

  add_foreign_key "partners_pal_additional_areas", ["partner_id"], "partners", ["id"], :name => "partners_pal_additional_areas_ibfk_1"
  add_foreign_key "partners_pal_additional_areas", ["pal_additional_area_id"], "pal_additional_areas", ["id"], :name => "partners_pal_additional_areas_ibfk_2"

  add_foreign_key "partners_pal_participation_levels", ["partner_id"], "partners", ["id"], :name => "partners_pal_participation_levels_ibfk_1"
  add_foreign_key "partners_pal_participation_levels", ["pal_participation_level_id"], "pal_participation_levels", ["id"], :name => "partners_pal_participation_levels_ibfk_2"

  add_foreign_key "partners_plan_types", ["partner_id"], "partners", ["id"], :name => "partners_plan_types_ibfk_1"
  add_foreign_key "partners_plan_types", ["plan_type_id"], "plan_types", ["id"], :name => "partners_plan_types_ibfk_2"

  add_foreign_key "partners_practices", ["partner_id"], "partners", ["id"], :name => "partners_practices_ibfk_1"
  add_foreign_key "partners_practices", ["practice_id"], "practices", ["id"], :name => "partners_practices_ibfk_2"

  add_foreign_key "partners_professions", ["partner_id"], "partners", ["id"], :name => "partners_professions_ibfk_1"
  add_foreign_key "partners_professions", ["profession_id"], "professions", ["id"], :name => "partners_professions_ibfk_2"

  add_foreign_key "partners_referral_fees", ["partner_id"], "partners", ["id"], :name => "partners_referral_fees_ibfk_1"
  add_foreign_key "partners_referral_fees", ["referral_fee_id"], "referral_fees", ["id"], :name => "partners_referral_fees_ibfk_2"

  add_foreign_key "partners_search_plan_types", ["partner_id"], "partners", ["id"], :name => "partners_search_plan_types_ibfk_1"
  add_foreign_key "partners_search_plan_types", ["search_plan_type_id"], "search_plan_types", ["id"], :name => "partners_search_plan_types_ibfk_2"

  add_foreign_key "partners_sponsor_types", ["partner_id"], "partners", ["id"], :name => "partners_sponsor_types_ibfk_1"
  add_foreign_key "partners_sponsor_types", ["sponsor_type_id"], "sponsor_types", ["id"], :name => "partners_sponsor_types_ibfk_2"

  add_foreign_key "plan_catch_all_employees", ["plan_id"], "plans", ["id"], :name => "plan_catch_all_employees_ibfk_1"
  add_foreign_key "plan_catch_all_employees", ["employee_type_id"], "employee_types", ["id"], :name => "plan_catch_all_employees_ibfk_2"

  add_foreign_key "plans", ["agency_id"], "agencies", ["id"], :name => "plans_ibfk_1"
  add_foreign_key "plans", ["plan_category_id"], "plan_categories", ["id"], :name => "plans_ibfk_2"

  add_foreign_key "publications", ["agency_id"], "agencies", ["id"], :name => "publications_ibfk_1"

  add_foreign_key "restrictions", ["agency_id"], "agencies", ["id"], :name => "restrictions_ibfk_1"
  add_foreign_key "restrictions", ["location_id"], "locations", ["id"], :name => "restrictions_ibfk_2"
  add_foreign_key "restrictions", ["plan_id"], "plans", ["id"], :name => "restrictions_ibfk_3"

  add_foreign_key "restrictions_cities", ["restriction_id"], "restrictions", ["id"], :name => "restrictions_cities_ibfk_1"
  add_foreign_key "restrictions_cities", ["city_id"], "cities", ["id"], :name => "restrictions_cities_ibfk_2"

  add_foreign_key "restrictions_counties", ["restriction_id"], "restrictions", ["id"], :name => "restrictions_counties_ibfk_1"
  add_foreign_key "restrictions_counties", ["county_id"], "counties", ["id"], :name => "restrictions_counties_ibfk_2"

  add_foreign_key "restrictions_states", ["restriction_id"], "restrictions", ["id"], :name => "restrictions_states_ibfk_1"

  add_foreign_key "restrictions_zips", ["restriction_id"], "restrictions", ["id"], :name => "restrictions_zips_ibfk_1"

  add_foreign_key "roles_users", ["user_id"], "users", ["id"], :name => "roles_users_ibfk_1"
  add_foreign_key "roles_users", ["role_id"], "roles", ["id"], :name => "roles_users_ibfk_2"

  add_foreign_key "zips", ["county_id"], "counties", ["id"], :name => "zips_ibfk_1"

end
