# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 12) do

  create_table "addresses", :force => true do |t|
    t.column "line1",           :string
    t.column "line2",           :string
    t.column "city",            :string
    t.column "state_abbrev",    :string
    t.column "zip",             :string
    t.column "agency_id",       :integer
    t.column "address_type_id", :integer
  end

  create_table "agencies", :force => true do |t|
    t.column "name",                 :string
    t.column "name2",                :string
    t.column "parent_id",            :integer
    t.column "description",          :text
    t.column "service_description",  :text
    t.column "phone",                :string
    t.column "tollfree",             :string
    t.column "fax",                  :string
    t.column "tty",                  :string
    t.column "url",                  :string
    t.column "url2",                 :string
    t.column "email",                :string
    t.column "hours_of_operation",   :string
    t.column "logistics",            :string
    t.column "comments",             :text
    t.column "data_source",          :string
    t.column "is_active",            :boolean
    t.column "legacy_code",          :string
    t.column "legacy_subcode",       :string
    t.column "has_restrictions",     :boolean
    t.column "has_geo_restrictions", :boolean
    t.column "agency_category_id",   :integer
    t.column "agency_type_id",       :integer
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
    t.column "updated_by",           :string
  end

  create_table "agency_categories", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "agency_types", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "contacts", :force => true do |t|
    t.column "first_name",       :string,  :limit => 80
    t.column "last_name",        :string,  :limit => 80
    t.column "middle_initial",   :string,  :limit => 2
    t.column "company",          :string
    t.column "line_1",           :string
    t.column "line_2",           :string
    t.column "city",             :string,  :limit => 50
    t.column "state_abbrev",     :string,  :limit => 2
    t.column "zip_code",         :string,  :limit => 10
    t.column "phone",            :string,  :limit => 20
    t.column "fax",              :string,  :limit => 20
    t.column "email",            :string
    t.column "url",              :string
    t.column "profession_id",    :integer
    t.column "profession_other", :string
    t.column "affiliations",     :string
    t.column "wants_npln",       :boolean
    t.column "wants_aaa",        :boolean
  end

  create_table "contents", :force => true do |t|
    t.column "url",        :string
    t.column "title",      :string
    t.column "content",    :text
    t.column "created_at", :string
    t.column "updated_at", :datetime
    t.column "updated_by", :string
  end

  create_table "help_nets", :force => true do |t|
    t.column "contact_id",       :integer
    t.column "exp_erisa_single", :boolean
    t.column "exp_erisa_multi",  :boolean
    t.column "exp_fed",          :boolean
    t.column "exp_state",        :boolean
    t.column "exp_church",       :boolean
    t.column "exp_other",        :string
    t.column "other_info",       :string
    t.column "wont_charge_fees", :boolean
  end

  create_table "images", :force => true do |t|
    t.column "db_file_id",   :integer
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "filename",     :string
    t.column "content_type", :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "aspect_ratio", :float
  end

  create_table "news", :force => true do |t|
    t.column "title",        :string
    t.column "intro",        :text
    t.column "article_url",  :string
    t.column "source_url",   :string
    t.column "is_internal",  :boolean
    t.column "body",         :text
    t.column "publish_date", :date
    t.column "archive_date", :date
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "updated_by",   :string
  end

  create_table "professions", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer
  end

  create_table "search_nets", :force => true do |t|
    t.column "contact_id",       :integer
    t.column "wont_charge_fees", :boolean
    t.column "info_plans",       :string
    t.column "info_geo",         :string
    t.column "info_industries",  :string
    t.column "info_referrals",   :string
  end

  create_table "states", :id => false, :force => true do |t|
    t.column "abbrev", :string, :limit => 2,  :default => "", :null => false
    t.column "name",   :string, :limit => 50
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
