class AddLostPlan < ActiveRecord::Migration
  def self.up
    add_column :counselings, :lost_plan, :boolean
    Content.create(
      :title => "Results for lost plans",
      :url => "lost_plan_resources",
      :is_active => true,
      :content => '<p class="border-bottom">&nbsp;</p> <h3>Here are some resources to help you locate or contact a former employer</h3> <p>People will often work long enough for one or more employers to earn a pension benefit, but leave that job before becoming eligible for a retirement benefit. In the interim, those people can move, change names or leave the workforce. Companies relocate and change names too. Companies will merge with other companies, split into multiple companies, or go out of business altogether. All of this activity can result in lost pensions for participants and lost participants for companies. These resources should help you track down lost companies or pensions.</p> <h4>Search at the Pension Benefit Guaranty Corporation</h4> <p>If you had a "defined benefit" pension plan that terminated after July 1 1974, these links may help you.</p> <div class="indent"> <p><a href="http://search.pbgc.gov/mp/">Search a list of the plan participants that the PBGC is looking for</a><br /> Enter your name or the name of your company to see if the PBGC is looking for you.</p> <p><a href="http://www.pbgc.gov/workers-retirees/find-your-pension-plan/content/page676.html">Search a list of pension plans currently managed by the PBGC</a><br /> Enter your plan or company name to see if the PBGC has information on your plan.</p> </div> <h4>Search at FreeERISA.com</h4> <p>FreeERISA.com manages a database of pension and retirement savings plan information that is based on &ldquo;ERISA form 5500 filings&rdquo; that private retirement plans must submit to the government. You will have to request a free registration before you can search for your plan. Here are some tips:</p> <div class="indent"> <p>If your company went out of business, terminated its retirement plan or stopped filing 5500s more than three or four years ago, the information will not be available online for free. To access this older information, you can contact FreeERISA.com to request a fee-for-service search.</p> <p>If you find the right company and the right plan, contact the plan administrator listed on the 5500 form. If you have the right company, but can&rsquo;t find the right plan, find a plan that is close in name or form to the one you are looking for and contact the plan administrator on the 5500 form for that plan. Review all attendant "schedules" for other service providers to the plan (actuaries, accountants, attorneys, etc.). They may have information about older plans and the companies that offered them.</p> <p>Use the link below to request a free password, then log in and enter a company name in the <strong>Search Benefit Filings</strong> field.</p> <p><a href="http://freeerisa.benefitspro.com/">Search for your plan at FreeERISA.com</a></p> </div> <h4>Download the "Finding a Lost Pension" booklet</h4> <p><a href="http://www.pbgc.gov/docs/Finding_A_Lost_Pension.pdf" class="indent">http://www.pbgc.gov/docs/Finding_A_Lost_Pension.pdf</a></p>')
      Content.find_by_url('lost_plan_resources').move_to_child_of(Content.root)

  end

  def self.down
    remove_column :counselings, :lost_plan
    Content.find_by_url('lost_plan_resources').destroy
  end
end
